# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    #driver: "gd"

    #resolvers:
     #   default:
     #       web_path:
      #          web_root: "%kernel.project_dir%/public"
      #          cache_prefix: media/cache
    loaders:
        default:
            filesystem:
                data_root: "%kernel.project_dir%/public/images/properties"
                bundle_resources:
                    enabled: true

    data_loader: default
    cache: default

    filter_sets:
        thumb:
            quality: 75
            filters:
                thumbnail:
                    size: [360,230]
                    mode: outbound
                    #allow_upscale: true
        medium:
            quality: 75
            filters:
                thumbnail:
                    size: [800,530]
                    mode: outbound
                    #allow_upscale: true
